baseURL: "https://jmkim93.github.io" 
title: Jungmin Kim
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: pubs/
          weight: 1
        - name: CV
          url: cv.pdf
          weight: 2
        - name: About
          url: about/
          weight: 3

params:
    description: "This website hosts Jungmin Kim's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: "Jungmin Kim"
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "Jan 02 2006"
    defaultTheme: auto
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["pubs"]
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jungmin Kim
          subtitle: Photonics researcher @ UW-Madison
          imageUrl: "picture.jpeg"
          imageWidth: 140
          imageHeight: 140
          buttons:
            - name: Publications
              url: pubs/
            - name: CV
              url: cv.pdf
            - name: About
              url: about/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=AGjDgr0AAAAJ&
        - name: researchgate
          url: https://www.researchgate.net/profile/Jungmin-Kim-10?ev=hdr_xprf
        - name: GitHub
          url: https://github.com/jmkim93
        - name: orcid
          url: https://orcid.org/0000-0001-8567-5338
        - name: linkedin
          url: https://www.linkedin.com/in/jmkim93
          
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jungmin Kim"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2